# mtconvy example settings file
# File is looked in following locations: current dir, directory with `mtconvy` executable, home directory

# Conversions to execute.
# Run `ffmpeg -decoders` or `ffmpeg -encoders` to see all supported codecs.
# All other streams just copied as is.
#conversions: { dts: eac3, real_288: ac3 }

# Audio bitrate. Default is 640k.
#audio_bitrate: 640k

# Suffix to be appended to output file name.
#suffix: CONVERTED

# Set to 'yes' to replace original files with converted ones after successful conversion.
# Original files will be renamed with `original_suffix` appended to their names and converted file will be renamed to original.
#replace_original: no
#original_suffix: ORIGINAL

# Strings to replace in original file name. Works only when `replace_original` is set to "yes".
#str_replace:
#  ".WEB-DL": ""
#  ".2160p": ".4k"


# Preferred languages for audio and subtitles to be default choice when selecting file streams. Streams could be re-selected per-file.
#languages: [UKR, ENG]


# Uncomment if you need custom paths to ffmpeg binaries.
#ffmpeg_path: /var/packages/ffmpeg/target/bin/ffmpeg
#ffprobe_path: /var/packages/ffmpeg/target/bin/ffprobe
