# mtconvy settings file
# File is looked in following locations: current dir, directory with `mtconvy` executable, home directory

# Conversions to execute.
# Run `ffmpeg -decoders` or `ffmpeg -encoders` to see all supported codecs.
# All other streams just copied as is.
#conversions: { dts: eac3, real_288: ac3 }

# Audio bitrate. Default is 640k.
#audio_bitrate: 640k

# Suffix to be appended to output file name.
#suffix: CONVERTED

# Preferred languages for audio and subtitles to be default choice when selecting file streams. Could be overridden per-file.
#languages: [UKR, ENG]

# Uncomment if you really need custom paths to ffmpeg binaries
#ffmpeg_path: /var/packages/ffmpeg/target/bin/ffmpeg
#ffprobe_path: /var/packages/ffmpeg/target/bin/ffprobe
